# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libmemcached-dev
        python -m pip install --upgrade pip
        python -m pip install ruff
        python -m pip install -e '.[tests]'
    - name: Lint with ruff
      run: |
        ruff format --diff ring tests setup.py
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Test with pytest
      run: |
        pytest
    - name: Stop containers
      run: docker-compose -f "docker-compose.yml" down

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
